/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedSplatRouteImport } from './routes/_authed/$'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as AuthedAddAccountRouteImport } from './routes/_authed/add-account'
import { Route as AuthedAppReleasesRouteImport } from './routes/_authed/app-releases'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedMerchantsRouteImport } from './routes/_authed/merchants'
import { Route as AuthedServicePointsRouteImport } from './routes/_authed/service-points'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSplatRoute = AuthedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAddAccountRoute = AuthedAddAccountRouteImport.update({
  id: '/add-account',
  path: '/add-account',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppReleasesRoute = AuthedAppReleasesRouteImport.update({
  id: '/app-releases',
  path: '/app-releases',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMerchantsRoute = AuthedMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicePointsRoute = AuthedServicePointsRouteImport.update({
  id: '/service-points',
  path: '/service-points',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$': typeof AuthedSplatRoute
  '/accounts': typeof AuthedAccountsRoute
  '/add-account': typeof AuthedAddAccountRoute
  '/app-releases': typeof AuthedAppReleasesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/merchants': typeof AuthedMerchantsRoute
  '/service-points': typeof AuthedServicePointsRoute
  '/users': typeof AuthedUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$': typeof AuthedSplatRoute
  '/accounts': typeof AuthedAccountsRoute
  '/add-account': typeof AuthedAddAccountRoute
  '/app-releases': typeof AuthedAppReleasesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/merchants': typeof AuthedMerchantsRoute
  '/service-points': typeof AuthedServicePointsRoute
  '/users': typeof AuthedUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/$': typeof AuthedSplatRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/add-account': typeof AuthedAddAccountRoute
  '/_authed/app-releases': typeof AuthedAppReleasesRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/merchants': typeof AuthedMerchantsRoute
  '/_authed/service-points': typeof AuthedServicePointsRoute
  '/_authed/users': typeof AuthedUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$'
    | '/accounts'
    | '/add-account'
    | '/app-releases'
    | '/dashboard'
    | '/merchants'
    | '/service-points'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$'
    | '/accounts'
    | '/add-account'
    | '/app-releases'
    | '/dashboard'
    | '/merchants'
    | '/service-points'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/$'
    | '/_authed/accounts'
    | '/_authed/add-account'
    | '/_authed/app-releases'
    | '/_authed/dashboard'
    | '/_authed/merchants'
    | '/_authed/service-points'
    | '/_authed/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$': {
      id: '/_authed/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthedSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/add-account': {
      id: '/_authed/add-account'
      path: '/add-account'
      fullPath: '/add-account'
      preLoaderRoute: typeof AuthedAddAccountRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app-releases': {
      id: '/_authed/app-releases'
      path: '/app-releases'
      fullPath: '/app-releases'
      preLoaderRoute: typeof AuthedAppReleasesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/merchants': {
      id: '/_authed/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AuthedMerchantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-points': {
      id: '/_authed/service-points'
      path: '/service-points'
      fullPath: '/service-points'
      preLoaderRoute: typeof AuthedServicePointsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSplatRoute: typeof AuthedSplatRoute
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedAddAccountRoute: typeof AuthedAddAccountRoute
  AuthedAppReleasesRoute: typeof AuthedAppReleasesRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedMerchantsRoute: typeof AuthedMerchantsRoute
  AuthedServicePointsRoute: typeof AuthedServicePointsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSplatRoute: AuthedSplatRoute,
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedAddAccountRoute: AuthedAddAccountRoute,
  AuthedAppReleasesRoute: AuthedAppReleasesRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedMerchantsRoute: AuthedMerchantsRoute,
  AuthedServicePointsRoute: AuthedServicePointsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
