/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthedSplatRouteImport } from './routes/_authed/$'
import { Route as AuthedAccountsRouteImport } from './routes/_authed/accounts'
import { Route as AuthedAppReleasesRouteImport } from './routes/_authed/app-releases'
import { Route as AuthedContractLinesRouteImport } from './routes/_authed/contract-lines'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedItemCategoriesRouteImport } from './routes/_authed/item-categories'
import { Route as AuthedMerchantsRouteImport } from './routes/_authed/merchants'
import { Route as AuthedProjectsRouteImport } from './routes/_authed/projects'
import { Route as AuthedServicePointsRouteImport } from './routes/_authed/service-points'
import { Route as AuthedUsersRouteImport } from './routes/_authed/users'
import { Route as AuthedProductsIndexRouteImport } from './routes/_authed/products/index'
import { Route as AuthedProductsProductIdRouteImport } from './routes/_authed/products/$productId'
import { Route as AuthedProductsNewRouteImport } from './routes/_authed/products/new'
import { Route as AuthedTerminalsIndexRouteImport } from './routes/_authed/terminals/index'
import { Route as AuthedTerminalsTerminalIdRouteImport } from './routes/_authed/terminals/$terminalId'
import { Route as AuthedWarehousesIndexRouteImport } from './routes/_authed/warehouses/index'
import { Route as AuthedWarehousesWarehouseIdRouteImport } from './routes/_authed/warehouses/$warehouseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedSplatRoute = AuthedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAppReleasesRoute = AuthedAppReleasesRouteImport.update({
  id: '/app-releases',
  path: '/app-releases',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContractLinesRoute = AuthedContractLinesRouteImport.update({
  id: '/contract-lines',
  path: '/contract-lines',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedItemCategoriesRoute = AuthedItemCategoriesRouteImport.update({
  id: '/item-categories',
  path: '/item-categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMerchantsRoute = AuthedMerchantsRouteImport.update({
  id: '/merchants',
  path: '/merchants',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProjectsRoute = AuthedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicePointsRoute = AuthedServicePointsRouteImport.update({
  id: '/service-points',
  path: '/service-points',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsIndexRoute = AuthedProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsProductIdRoute = AuthedProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsNewRoute = AuthedProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTerminalsIndexRoute = AuthedTerminalsIndexRouteImport.update({
  id: '/terminals/',
  path: '/terminals/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTerminalsTerminalIdRoute =
  AuthedTerminalsTerminalIdRouteImport.update({
    id: '/terminals/$terminalId',
    path: '/terminals/$terminalId',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedWarehousesIndexRoute = AuthedWarehousesIndexRouteImport.update({
  id: '/warehouses/',
  path: '/warehouses/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWarehousesWarehouseIdRoute =
  AuthedWarehousesWarehouseIdRouteImport.update({
    id: '/warehouses/$warehouseId',
    path: '/warehouses/$warehouseId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$': typeof AuthedSplatRoute
  '/accounts': typeof AuthedAccountsRoute
  '/app-releases': typeof AuthedAppReleasesRoute
  '/contract-lines': typeof AuthedContractLinesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/item-categories': typeof AuthedItemCategoriesRoute
  '/merchants': typeof AuthedMerchantsRoute
  '/projects': typeof AuthedProjectsRoute
  '/service-points': typeof AuthedServicePointsRoute
  '/users': typeof AuthedUsersRoute
  '/products/$productId': typeof AuthedProductsProductIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/terminals/$terminalId': typeof AuthedTerminalsTerminalIdRoute
  '/warehouses/$warehouseId': typeof AuthedWarehousesWarehouseIdRoute
  '/products/': typeof AuthedProductsIndexRoute
  '/terminals/': typeof AuthedTerminalsIndexRoute
  '/warehouses/': typeof AuthedWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/$': typeof AuthedSplatRoute
  '/accounts': typeof AuthedAccountsRoute
  '/app-releases': typeof AuthedAppReleasesRoute
  '/contract-lines': typeof AuthedContractLinesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/item-categories': typeof AuthedItemCategoriesRoute
  '/merchants': typeof AuthedMerchantsRoute
  '/projects': typeof AuthedProjectsRoute
  '/service-points': typeof AuthedServicePointsRoute
  '/users': typeof AuthedUsersRoute
  '/products/$productId': typeof AuthedProductsProductIdRoute
  '/products/new': typeof AuthedProductsNewRoute
  '/terminals/$terminalId': typeof AuthedTerminalsTerminalIdRoute
  '/warehouses/$warehouseId': typeof AuthedWarehousesWarehouseIdRoute
  '/products': typeof AuthedProductsIndexRoute
  '/terminals': typeof AuthedTerminalsIndexRoute
  '/warehouses': typeof AuthedWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authed/$': typeof AuthedSplatRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/app-releases': typeof AuthedAppReleasesRoute
  '/_authed/contract-lines': typeof AuthedContractLinesRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/item-categories': typeof AuthedItemCategoriesRoute
  '/_authed/merchants': typeof AuthedMerchantsRoute
  '/_authed/projects': typeof AuthedProjectsRoute
  '/_authed/service-points': typeof AuthedServicePointsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/products/$productId': typeof AuthedProductsProductIdRoute
  '/_authed/products/new': typeof AuthedProductsNewRoute
  '/_authed/terminals/$terminalId': typeof AuthedTerminalsTerminalIdRoute
  '/_authed/warehouses/$warehouseId': typeof AuthedWarehousesWarehouseIdRoute
  '/_authed/products/': typeof AuthedProductsIndexRoute
  '/_authed/terminals/': typeof AuthedTerminalsIndexRoute
  '/_authed/warehouses/': typeof AuthedWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$'
    | '/accounts'
    | '/app-releases'
    | '/contract-lines'
    | '/dashboard'
    | '/item-categories'
    | '/merchants'
    | '/projects'
    | '/service-points'
    | '/users'
    | '/products/$productId'
    | '/products/new'
    | '/terminals/$terminalId'
    | '/warehouses/$warehouseId'
    | '/products/'
    | '/terminals/'
    | '/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/$'
    | '/accounts'
    | '/app-releases'
    | '/contract-lines'
    | '/dashboard'
    | '/item-categories'
    | '/merchants'
    | '/projects'
    | '/service-points'
    | '/users'
    | '/products/$productId'
    | '/products/new'
    | '/terminals/$terminalId'
    | '/warehouses/$warehouseId'
    | '/products'
    | '/terminals'
    | '/warehouses'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authed/$'
    | '/_authed/accounts'
    | '/_authed/app-releases'
    | '/_authed/contract-lines'
    | '/_authed/dashboard'
    | '/_authed/item-categories'
    | '/_authed/merchants'
    | '/_authed/projects'
    | '/_authed/service-points'
    | '/_authed/users'
    | '/_authed/products/$productId'
    | '/_authed/products/new'
    | '/_authed/terminals/$terminalId'
    | '/_authed/warehouses/$warehouseId'
    | '/_authed/products/'
    | '/_authed/terminals/'
    | '/_authed/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/$': {
      id: '/_authed/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthedSplatRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/app-releases': {
      id: '/_authed/app-releases'
      path: '/app-releases'
      fullPath: '/app-releases'
      preLoaderRoute: typeof AuthedAppReleasesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contract-lines': {
      id: '/_authed/contract-lines'
      path: '/contract-lines'
      fullPath: '/contract-lines'
      preLoaderRoute: typeof AuthedContractLinesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/item-categories': {
      id: '/_authed/item-categories'
      path: '/item-categories'
      fullPath: '/item-categories'
      preLoaderRoute: typeof AuthedItemCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/merchants': {
      id: '/_authed/merchants'
      path: '/merchants'
      fullPath: '/merchants'
      preLoaderRoute: typeof AuthedMerchantsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/projects': {
      id: '/_authed/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthedProjectsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/service-points': {
      id: '/_authed/service-points'
      path: '/service-points'
      fullPath: '/service-points'
      preLoaderRoute: typeof AuthedServicePointsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/': {
      id: '/_authed/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthedProductsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/$productId': {
      id: '/_authed/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthedProductsProductIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products/new': {
      id: '/_authed/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthedProductsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/terminals/': {
      id: '/_authed/terminals/'
      path: '/terminals'
      fullPath: '/terminals/'
      preLoaderRoute: typeof AuthedTerminalsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/terminals/$terminalId': {
      id: '/_authed/terminals/$terminalId'
      path: '/terminals/$terminalId'
      fullPath: '/terminals/$terminalId'
      preLoaderRoute: typeof AuthedTerminalsTerminalIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/warehouses/': {
      id: '/_authed/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses/'
      preLoaderRoute: typeof AuthedWarehousesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/warehouses/$warehouseId': {
      id: '/_authed/warehouses/$warehouseId'
      path: '/warehouses/$warehouseId'
      fullPath: '/warehouses/$warehouseId'
      preLoaderRoute: typeof AuthedWarehousesWarehouseIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedSplatRoute: typeof AuthedSplatRoute
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedAppReleasesRoute: typeof AuthedAppReleasesRoute
  AuthedContractLinesRoute: typeof AuthedContractLinesRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedItemCategoriesRoute: typeof AuthedItemCategoriesRoute
  AuthedMerchantsRoute: typeof AuthedMerchantsRoute
  AuthedProjectsRoute: typeof AuthedProjectsRoute
  AuthedServicePointsRoute: typeof AuthedServicePointsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedProductsProductIdRoute: typeof AuthedProductsProductIdRoute
  AuthedProductsNewRoute: typeof AuthedProductsNewRoute
  AuthedTerminalsTerminalIdRoute: typeof AuthedTerminalsTerminalIdRoute
  AuthedWarehousesWarehouseIdRoute: typeof AuthedWarehousesWarehouseIdRoute
  AuthedProductsIndexRoute: typeof AuthedProductsIndexRoute
  AuthedTerminalsIndexRoute: typeof AuthedTerminalsIndexRoute
  AuthedWarehousesIndexRoute: typeof AuthedWarehousesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedSplatRoute: AuthedSplatRoute,
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedAppReleasesRoute: AuthedAppReleasesRoute,
  AuthedContractLinesRoute: AuthedContractLinesRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedItemCategoriesRoute: AuthedItemCategoriesRoute,
  AuthedMerchantsRoute: AuthedMerchantsRoute,
  AuthedProjectsRoute: AuthedProjectsRoute,
  AuthedServicePointsRoute: AuthedServicePointsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedProductsProductIdRoute: AuthedProductsProductIdRoute,
  AuthedProductsNewRoute: AuthedProductsNewRoute,
  AuthedTerminalsTerminalIdRoute: AuthedTerminalsTerminalIdRoute,
  AuthedWarehousesWarehouseIdRoute: AuthedWarehousesWarehouseIdRoute,
  AuthedProductsIndexRoute: AuthedProductsIndexRoute,
  AuthedTerminalsIndexRoute: AuthedTerminalsIndexRoute,
  AuthedWarehousesIndexRoute: AuthedWarehousesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
